# Kaggle 環境専用パス設定（/kaggle/working, /kaggle/input を前提）
paths:
  work_dir: /kaggle/working
  input_dir: /kaggle/input
  output_dir: ${paths.work_dir}/outputs
  models_dir: ${paths.input_dir}/rsna2025-weights
  precompute_dir: ${paths.input_dir}/rsna2025-precompute
  preds_dir: ${paths.output_dir}/preds
  oof_dir: ${paths.output_dir}/oof

wandb:
  enabled: false
  mode: disabled
